### PR TITLE
Fix/Correct linting

### PR DESCRIPTION
**Pull request by tekktrik**

### CODE REVIEW

**Comment by theendlessriver13** [comment]
f-strings seem to be not supported by all circuitpython boards see: https://github.com/adafruit/Adafruit_CircuitPython_GPS/pull/67#issuecomment-926913495

So I think except inside the tests they unfortunatelly can't be used.

The f-string suggestion from pylint should be disabled though (ca3885a) ?

**Comment by tekktrik** [comment]
Sounds good, I can add that to the file instead, thanks for the heads up!

**Comment by tekktrik** [comment]
And I'm not sure, I found it on https://circuitpython.org/contributing/library-infrastructure-issues and that's what came up when I ran pylint.  If it's something else I'd be happy to work on it!

**Comment by tekktrik** [comment]
Please don't approve, pending changes per discussion found here:  https://github.com/adafruit/Adafruit_CircuitPython_Fingerprint/pull/35#pullrequestreview-795630349

**Comment by tekktrik** [comment]
Closing per discussion: https://github.com/adafruit/Adafruit_CircuitPython_Fingerprint/pull/35#issuecomment-957938005

**Pull request closed without merging**
