### PR TITLE
Add I2C support and various example fixes

### PR DESCRIPTION
**Pull request by ladyada**
Added GPS_I2C for interfacing with simple I2C implementations of GPS modules
Updated all examples to have UART, pyserial and I2C definitions
Fixed weird huge timeouts in UART examples
Removed 'computer' datalogging demo and merged it with the non-computer datalogging demo
Fixed datalogging demo which was missing some imports. Tested on Windows+I2C and Feather M4
Fixed RTC demo, was based on old circuitpython, tested with I2C GPS
Parser now accepts $GN NMEA's used in more modern modules

### CODE REVIEW

**Comment by caternuson** [comment]
Looks like you are wanting to not make this a breaking change? Otherwise could maybe refactor the classes more like other multi-interface drivers do.

**Current** (UART only):
```python
GPS
```
**Refactor** (breaking)
```python
GPS
GPS_UART(GPS)
GPS_I2C(GPS)
```

**Comment by ladyada** [comment]
correct, also because theres one standard UART interface, but there may be variable I2C/SPI interfaces (they aren't standardized). default `GPS` should be UART!

**Comment by caternuson** [comment]
ah, ok. should `GPS_I2C` be renamed then to reflect that? as is, sounds generic. as if it is standardized.

**Comment by ladyada** [comment]
could rename it GPS_GTopI2C ?

**Comment by caternuson** [comment]
yah. something like that. i don't know the specifics enough to suggest any better. just concerned about implying that there is a standard I2C interface by having just `GPS_I2C`. and if/when more interfaces get added, what would they be named.

sounds like GTop is the specific interface here?

**Comment by ladyada** [comment]
yeah its used for GTop modules 🤷‍♂ :)
ill submit changes

**Comment by ladyada** [comment]
@caternuson finally had time to do this! please check it out - tested :)

**Comment by caternuson** [comment]
Yep. Looks good. Just a simple naming convention, but seems like a good idea.

**Comment by ladyada** [comment]
yaaayyy! doing SPI next

**Pull request merged**
